<?php
// $this->headScript()->appendFile($this->assetUrl('js/index-properties.js', 'TypesenseSearch'));
// $this->headLink()->appendStylesheet($this->assetUrl('css/index-properties.css', 'TypesenseSearch'));

// $recreateIndexAction = $this->url('admin/recreate-index', ['controller' => 'SearchController', 'action' => 'recreateIndex'], true);
// $dropIndexAction = $this->url('admin/drop-index', ['controller' => 'SearchController', 'action' => 'dropIndex'], true);
?>

<?php echo $this->formCollection($form, false); ?>